// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/salary/v1/salary.proto

package salaryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SalaryService_CalculateNetSalary_FullMethodName      = "/salary.v1.SalaryService/CalculateNetSalary"
	SalaryService_GetSalaryStatsByCountry_FullMethodName = "/salary.v1.SalaryService/GetSalaryStatsByCountry"
	SalaryService_GetAvgSalaryByJobTitle_FullMethodName  = "/salary.v1.SalaryService/GetAvgSalaryByJobTitle"
)

// SalaryServiceClient is the client API for SalaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SalaryService provides salary calculation and metrics functionality
type SalaryServiceClient interface {
	// CalculateNetSalary calculates the net salary for an employee
	CalculateNetSalary(ctx context.Context, in *CalculateNetSalaryRequest, opts ...grpc.CallOption) (*CalculateNetSalaryResponse, error)
	// GetSalaryStatsByCountry returns salary statistics for a country
	GetSalaryStatsByCountry(ctx context.Context, in *GetSalaryStatsByCountryRequest, opts ...grpc.CallOption) (*SalaryStatsResponse, error)
	// GetAvgSalaryByJobTitle returns average salary for a job title
	GetAvgSalaryByJobTitle(ctx context.Context, in *GetAvgSalaryByJobTitleRequest, opts ...grpc.CallOption) (*JobTitleSalaryStatsResponse, error)
}

type salaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSalaryServiceClient(cc grpc.ClientConnInterface) SalaryServiceClient {
	return &salaryServiceClient{cc}
}

func (c *salaryServiceClient) CalculateNetSalary(ctx context.Context, in *CalculateNetSalaryRequest, opts ...grpc.CallOption) (*CalculateNetSalaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateNetSalaryResponse)
	err := c.cc.Invoke(ctx, SalaryService_CalculateNetSalary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *salaryServiceClient) GetSalaryStatsByCountry(ctx context.Context, in *GetSalaryStatsByCountryRequest, opts ...grpc.CallOption) (*SalaryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SalaryStatsResponse)
	err := c.cc.Invoke(ctx, SalaryService_GetSalaryStatsByCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *salaryServiceClient) GetAvgSalaryByJobTitle(ctx context.Context, in *GetAvgSalaryByJobTitleRequest, opts ...grpc.CallOption) (*JobTitleSalaryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobTitleSalaryStatsResponse)
	err := c.cc.Invoke(ctx, SalaryService_GetAvgSalaryByJobTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SalaryServiceServer is the server API for SalaryService service.
// All implementations must embed UnimplementedSalaryServiceServer
// for forward compatibility.
//
// SalaryService provides salary calculation and metrics functionality
type SalaryServiceServer interface {
	// CalculateNetSalary calculates the net salary for an employee
	CalculateNetSalary(context.Context, *CalculateNetSalaryRequest) (*CalculateNetSalaryResponse, error)
	// GetSalaryStatsByCountry returns salary statistics for a country
	GetSalaryStatsByCountry(context.Context, *GetSalaryStatsByCountryRequest) (*SalaryStatsResponse, error)
	// GetAvgSalaryByJobTitle returns average salary for a job title
	GetAvgSalaryByJobTitle(context.Context, *GetAvgSalaryByJobTitleRequest) (*JobTitleSalaryStatsResponse, error)
	mustEmbedUnimplementedSalaryServiceServer()
}

// UnimplementedSalaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSalaryServiceServer struct{}

func (UnimplementedSalaryServiceServer) CalculateNetSalary(context.Context, *CalculateNetSalaryRequest) (*CalculateNetSalaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateNetSalary not implemented")
}
func (UnimplementedSalaryServiceServer) GetSalaryStatsByCountry(context.Context, *GetSalaryStatsByCountryRequest) (*SalaryStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSalaryStatsByCountry not implemented")
}
func (UnimplementedSalaryServiceServer) GetAvgSalaryByJobTitle(context.Context, *GetAvgSalaryByJobTitleRequest) (*JobTitleSalaryStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvgSalaryByJobTitle not implemented")
}
func (UnimplementedSalaryServiceServer) mustEmbedUnimplementedSalaryServiceServer() {}
func (UnimplementedSalaryServiceServer) testEmbeddedByValue()                       {}

// UnsafeSalaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SalaryServiceServer will
// result in compilation errors.
type UnsafeSalaryServiceServer interface {
	mustEmbedUnimplementedSalaryServiceServer()
}

func RegisterSalaryServiceServer(s grpc.ServiceRegistrar, srv SalaryServiceServer) {
	// If the following call panics, it indicates UnimplementedSalaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SalaryService_ServiceDesc, srv)
}

func _SalaryService_CalculateNetSalary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateNetSalaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalaryServiceServer).CalculateNetSalary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SalaryService_CalculateNetSalary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalaryServiceServer).CalculateNetSalary(ctx, req.(*CalculateNetSalaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SalaryService_GetSalaryStatsByCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSalaryStatsByCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalaryServiceServer).GetSalaryStatsByCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SalaryService_GetSalaryStatsByCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalaryServiceServer).GetSalaryStatsByCountry(ctx, req.(*GetSalaryStatsByCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SalaryService_GetAvgSalaryByJobTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvgSalaryByJobTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SalaryServiceServer).GetAvgSalaryByJobTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SalaryService_GetAvgSalaryByJobTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SalaryServiceServer).GetAvgSalaryByJobTitle(ctx, req.(*GetAvgSalaryByJobTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SalaryService_ServiceDesc is the grpc.ServiceDesc for SalaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SalaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "salary.v1.SalaryService",
	HandlerType: (*SalaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateNetSalary",
			Handler:    _SalaryService_CalculateNetSalary_Handler,
		},
		{
			MethodName: "GetSalaryStatsByCountry",
			Handler:    _SalaryService_GetSalaryStatsByCountry_Handler,
		},
		{
			MethodName: "GetAvgSalaryByJobTitle",
			Handler:    _SalaryService_GetAvgSalaryByJobTitle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/salary/v1/salary.proto",
}
