// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/salary/v1/salary.proto

package salaryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateNetSalaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    string                 `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateNetSalaryRequest) Reset() {
	*x = CalculateNetSalaryRequest{}
	mi := &file_proto_salary_v1_salary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateNetSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateNetSalaryRequest) ProtoMessage() {}

func (x *CalculateNetSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salary_v1_salary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateNetSalaryRequest.ProtoReflect.Descriptor instead.
func (*CalculateNetSalaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_salary_v1_salary_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateNetSalaryRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

type CalculateNetSalaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrossSalary   string                 `protobuf:"bytes,1,opt,name=gross_salary,json=grossSalary,proto3" json:"gross_salary,omitempty"`
	TaxRate       string                 `protobuf:"bytes,2,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	TaxAmount     string                 `protobuf:"bytes,3,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	NetSalary     string                 `protobuf:"bytes,4,opt,name=net_salary,json=netSalary,proto3" json:"net_salary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateNetSalaryResponse) Reset() {
	*x = CalculateNetSalaryResponse{}
	mi := &file_proto_salary_v1_salary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateNetSalaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateNetSalaryResponse) ProtoMessage() {}

func (x *CalculateNetSalaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salary_v1_salary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateNetSalaryResponse.ProtoReflect.Descriptor instead.
func (*CalculateNetSalaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_salary_v1_salary_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateNetSalaryResponse) GetGrossSalary() string {
	if x != nil {
		return x.GrossSalary
	}
	return ""
}

func (x *CalculateNetSalaryResponse) GetTaxRate() string {
	if x != nil {
		return x.TaxRate
	}
	return ""
}

func (x *CalculateNetSalaryResponse) GetTaxAmount() string {
	if x != nil {
		return x.TaxAmount
	}
	return ""
}

func (x *CalculateNetSalaryResponse) GetNetSalary() string {
	if x != nil {
		return x.NetSalary
	}
	return ""
}

type GetSalaryStatsByCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalaryStatsByCountryRequest) Reset() {
	*x = GetSalaryStatsByCountryRequest{}
	mi := &file_proto_salary_v1_salary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalaryStatsByCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalaryStatsByCountryRequest) ProtoMessage() {}

func (x *GetSalaryStatsByCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salary_v1_salary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalaryStatsByCountryRequest.ProtoReflect.Descriptor instead.
func (*GetSalaryStatsByCountryRequest) Descriptor() ([]byte, []int) {
	return file_proto_salary_v1_salary_proto_rawDescGZIP(), []int{2}
}

func (x *GetSalaryStatsByCountryRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type SalaryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinSalary     string                 `protobuf:"bytes,1,opt,name=min_salary,json=minSalary,proto3" json:"min_salary,omitempty"`
	MaxSalary     string                 `protobuf:"bytes,2,opt,name=max_salary,json=maxSalary,proto3" json:"max_salary,omitempty"`
	AvgSalary     string                 `protobuf:"bytes,3,opt,name=avg_salary,json=avgSalary,proto3" json:"avg_salary,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SalaryStatsResponse) Reset() {
	*x = SalaryStatsResponse{}
	mi := &file_proto_salary_v1_salary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SalaryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SalaryStatsResponse) ProtoMessage() {}

func (x *SalaryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salary_v1_salary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SalaryStatsResponse.ProtoReflect.Descriptor instead.
func (*SalaryStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_salary_v1_salary_proto_rawDescGZIP(), []int{3}
}

func (x *SalaryStatsResponse) GetMinSalary() string {
	if x != nil {
		return x.MinSalary
	}
	return ""
}

func (x *SalaryStatsResponse) GetMaxSalary() string {
	if x != nil {
		return x.MaxSalary
	}
	return ""
}

func (x *SalaryStatsResponse) GetAvgSalary() string {
	if x != nil {
		return x.AvgSalary
	}
	return ""
}

func (x *SalaryStatsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetAvgSalaryByJobTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobTitle      string                 `protobuf:"bytes,1,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvgSalaryByJobTitleRequest) Reset() {
	*x = GetAvgSalaryByJobTitleRequest{}
	mi := &file_proto_salary_v1_salary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvgSalaryByJobTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvgSalaryByJobTitleRequest) ProtoMessage() {}

func (x *GetAvgSalaryByJobTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salary_v1_salary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvgSalaryByJobTitleRequest.ProtoReflect.Descriptor instead.
func (*GetAvgSalaryByJobTitleRequest) Descriptor() ([]byte, []int) {
	return file_proto_salary_v1_salary_proto_rawDescGZIP(), []int{4}
}

func (x *GetAvgSalaryByJobTitleRequest) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

type JobTitleSalaryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobTitle      string                 `protobuf:"bytes,1,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	AvgSalary     string                 `protobuf:"bytes,2,opt,name=avg_salary,json=avgSalary,proto3" json:"avg_salary,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobTitleSalaryStatsResponse) Reset() {
	*x = JobTitleSalaryStatsResponse{}
	mi := &file_proto_salary_v1_salary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTitleSalaryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTitleSalaryStatsResponse) ProtoMessage() {}

func (x *JobTitleSalaryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_salary_v1_salary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTitleSalaryStatsResponse.ProtoReflect.Descriptor instead.
func (*JobTitleSalaryStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_salary_v1_salary_proto_rawDescGZIP(), []int{5}
}

func (x *JobTitleSalaryStatsResponse) GetJobTitle() string {
	if x != nil {
		return x.JobTitle
	}
	return ""
}

func (x *JobTitleSalaryStatsResponse) GetAvgSalary() string {
	if x != nil {
		return x.AvgSalary
	}
	return ""
}

func (x *JobTitleSalaryStatsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_salary_v1_salary_proto protoreflect.FileDescriptor

const file_proto_salary_v1_salary_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/salary/v1/salary.proto\x12\tsalary.v1\"<\n" +
	"\x19CalculateNetSalaryRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\"\x98\x01\n" +
	"\x1aCalculateNetSalaryResponse\x12!\n" +
	"\fgross_salary\x18\x01 \x01(\tR\vgrossSalary\x12\x19\n" +
	"\btax_rate\x18\x02 \x01(\tR\ataxRate\x12\x1d\n" +
	"\n" +
	"tax_amount\x18\x03 \x01(\tR\ttaxAmount\x12\x1d\n" +
	"\n" +
	"net_salary\x18\x04 \x01(\tR\tnetSalary\":\n" +
	"\x1eGetSalaryStatsByCountryRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\"\x88\x01\n" +
	"\x13SalaryStatsResponse\x12\x1d\n" +
	"\n" +
	"min_salary\x18\x01 \x01(\tR\tminSalary\x12\x1d\n" +
	"\n" +
	"max_salary\x18\x02 \x01(\tR\tmaxSalary\x12\x1d\n" +
	"\n" +
	"avg_salary\x18\x03 \x01(\tR\tavgSalary\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"<\n" +
	"\x1dGetAvgSalaryByJobTitleRequest\x12\x1b\n" +
	"\tjob_title\x18\x01 \x01(\tR\bjobTitle\"o\n" +
	"\x1bJobTitleSalaryStatsResponse\x12\x1b\n" +
	"\tjob_title\x18\x01 \x01(\tR\bjobTitle\x12\x1d\n" +
	"\n" +
	"avg_salary\x18\x02 \x01(\tR\tavgSalary\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count2\xc4\x02\n" +
	"\rSalaryService\x12a\n" +
	"\x12CalculateNetSalary\x12$.salary.v1.CalculateNetSalaryRequest\x1a%.salary.v1.CalculateNetSalaryResponse\x12d\n" +
	"\x17GetSalaryStatsByCountry\x12).salary.v1.GetSalaryStatsByCountryRequest\x1a\x1e.salary.v1.SalaryStatsResponse\x12j\n" +
	"\x16GetAvgSalaryByJobTitle\x12(.salary.v1.GetAvgSalaryByJobTitleRequest\x1a&.salary.v1.JobTitleSalaryStatsResponseB.Z,github.com/employee-proto/salary/v1;salaryv1b\x06proto3"

var (
	file_proto_salary_v1_salary_proto_rawDescOnce sync.Once
	file_proto_salary_v1_salary_proto_rawDescData []byte
)

func file_proto_salary_v1_salary_proto_rawDescGZIP() []byte {
	file_proto_salary_v1_salary_proto_rawDescOnce.Do(func() {
		file_proto_salary_v1_salary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_salary_v1_salary_proto_rawDesc), len(file_proto_salary_v1_salary_proto_rawDesc)))
	})
	return file_proto_salary_v1_salary_proto_rawDescData
}

var file_proto_salary_v1_salary_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_salary_v1_salary_proto_goTypes = []any{
	(*CalculateNetSalaryRequest)(nil),      // 0: salary.v1.CalculateNetSalaryRequest
	(*CalculateNetSalaryResponse)(nil),     // 1: salary.v1.CalculateNetSalaryResponse
	(*GetSalaryStatsByCountryRequest)(nil), // 2: salary.v1.GetSalaryStatsByCountryRequest
	(*SalaryStatsResponse)(nil),            // 3: salary.v1.SalaryStatsResponse
	(*GetAvgSalaryByJobTitleRequest)(nil),  // 4: salary.v1.GetAvgSalaryByJobTitleRequest
	(*JobTitleSalaryStatsResponse)(nil),    // 5: salary.v1.JobTitleSalaryStatsResponse
}
var file_proto_salary_v1_salary_proto_depIdxs = []int32{
	0, // 0: salary.v1.SalaryService.CalculateNetSalary:input_type -> salary.v1.CalculateNetSalaryRequest
	2, // 1: salary.v1.SalaryService.GetSalaryStatsByCountry:input_type -> salary.v1.GetSalaryStatsByCountryRequest
	4, // 2: salary.v1.SalaryService.GetAvgSalaryByJobTitle:input_type -> salary.v1.GetAvgSalaryByJobTitleRequest
	1, // 3: salary.v1.SalaryService.CalculateNetSalary:output_type -> salary.v1.CalculateNetSalaryResponse
	3, // 4: salary.v1.SalaryService.GetSalaryStatsByCountry:output_type -> salary.v1.SalaryStatsResponse
	5, // 5: salary.v1.SalaryService.GetAvgSalaryByJobTitle:output_type -> salary.v1.JobTitleSalaryStatsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_salary_v1_salary_proto_init() }
func file_proto_salary_v1_salary_proto_init() {
	if File_proto_salary_v1_salary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_salary_v1_salary_proto_rawDesc), len(file_proto_salary_v1_salary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_salary_v1_salary_proto_goTypes,
		DependencyIndexes: file_proto_salary_v1_salary_proto_depIdxs,
		MessageInfos:      file_proto_salary_v1_salary_proto_msgTypes,
	}.Build()
	File_proto_salary_v1_salary_proto = out.File
	file_proto_salary_v1_salary_proto_goTypes = nil
	file_proto_salary_v1_salary_proto_depIdxs = nil
}
